// Form number → ISO title map
export const FORM_NUMBERS = {
  '102': 'Class Attendance Register',
  '103': 'Timetable Preparation Report',
  '104': 'Academic Calendar Compliance',
  '105': 'Faculty Activity Report',
  '106': 'Internship Offer Letter Register',
  '107': 'Internship Completion Certificate Register',
  '108': 'Project/Innovation Proposal',
  '109': 'Faculty Self-Appraisal Form',
  '110': 'Student Portfolio',
  '111': 'Internship Feedback Form',
  '112': 'Industry Mentor Details',
  '113': 'Co-curricular Activity Report',
  '114': 'Budget Proposal Form',
  '115': 'Expenditure Statement',
  '116': 'Budget Utilization Report',
  '117': 'Course Delivery Plan',
  '118': 'Course Exit Survey',
  '119': 'Department Academic Review',
  '126': 'Faculty Research Activity',
  '136': 'Syllabus Coverage Report',
  '158': 'Student Feedback Report',
  '159': 'Slow/Advanced Learner Report',
  '172': 'Tutorial/Extra Class Report',
  '174': 'Class Teacher Activity Report',
  '177': 'Project Review Report',
  '178': 'Project Completion Report',
  '179': 'Research Activity Report',
  '180': 'Innovation & Patent Report',
  '182': 'Lab Experiment Observation',
  '183': 'Student Achievement Record',
  '184': 'CO-PO Mapping Report',
  '185': 'Program Educational Objectives Review',
  '186': 'Academic Performance Analysis',
  '187': 'Board of Studies Meeting Minutes',
  '188': 'Academic Audit Report',
  '189': 'Faculty Seminar/Workshop Report',
  '190': 'Remedial Classes Report',
  '191': 'University Result Analysis',
  '193': 'Student Mentor Report',
  '194': 'Course Outcome Attainment',
  '195': 'Continuous Internal Evaluation',
  '196': 'Assignment Evaluation Record',
  '197': 'Industry Visit Report',
  '655-A': 'Faculty Leave Application',
  '655-B': 'Faculty Duty Leave Form',
  '656': 'Faculty Research Publication',
  '811': 'Alumni Interaction Record',
  '812': 'Alumni Contact Directory',
  '813': 'Alumni Event Report',
  '814': 'Student Progression Record',
  '815': 'Placement / Higher Study Record',
  '816': 'Student Portfolio Showcase',
  '817': 'Alumni Feedback Register',
  '818': 'Distinguished Alumni Record',
};
